import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };
export const learnerProfiles = sqliteTable("learner_profiles", { id: text("id").primaryKey(), displayName: text("display_name").notNull(), learningGoal: text("learning_goal").notNull(), weeklyHours: integer("weekly_hours").notNull(), timezone: text("timezone").notNull(), currentProject: text("current_project"), ...timestamps });
export const competencies = sqliteTable("competencies", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description").notNull(), priority: text("priority").notNull(), prerequisitesJson: text("prerequisites_json").notNull(), ...timestamps });
export const competencyStates = sqliteTable("competency_states", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), mastery: integer("mastery").notNull().default(0), confidence: integer("confidence").notNull().default(0), lastAssessedAt: text("last_assessed_at"), reviewDueAt: text("review_due_at"), rationale: text("rationale").notNull(), ...timestamps }, (t) => [uniqueIndex("uq_state_learner_competency").on(t.learnerId, t.competencyId), index("idx_state_learner_review").on(t.learnerId, t.reviewDueAt)]);
export const learningTasks = sqliteTable("learning_tasks", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), title: text("title").notNull(), instruction: text("instruction").notNull(), expectedOutput: text("expected_output").notNull(), rubricJson: text("rubric_json").notNull(), status: text("status").notNull(), sourceUnitId: text("source_unit_id"), ...timestamps }, (t) => [index("idx_task_learner_status").on(t.learnerId, t.status, t.updatedAt)]);
export const evidence = sqliteTable("evidence", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), taskId: text("task_id").references(() => learningTasks.id), type: text("type").notNull(), content: text("content").notNull(), score: integer("score"), feedback: text("feedback"), ...timestamps }, (t) => [index("idx_evidence_learner_competency").on(t.learnerId, t.competencyId, t.createdAt)]);
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), role: text("role").notNull(), content: text("content").notNull(), source: text("source"), ...timestamps }, (t) => [index("idx_conversation_learner_created").on(t.learnerId, t.createdAt)]);
export const assessments = sqliteTable("assessments", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), question: text("question").notNull(), rubricJson: text("rubric_json").notNull(), answer: text("answer"), score: integer("score"), feedback: text("feedback"), status: text("status").notNull(), ...timestamps }, (t) => [index("idx_assessment_learner_status").on(t.learnerId, t.status, t.createdAt)]);
export const sourceDocuments = sqliteTable("source_documents", { id: text("id").primaryKey(), title: text("title").notNull(), url: text("url").notNull(), sourceType: text("source_type").notNull(), versionLabel: text("version_label"), reviewedAt: text("reviewed_at"), trustLevel: text("trust_level").notNull(), status: text("status").notNull(), topicIdsJson: text("topic_ids_json").notNull(), summary: text("summary"), ...timestamps }, (t) => [uniqueIndex("uq_source_url_version").on(t.url, t.versionLabel)]);
