"use client";
import { useState } from "react";
import { notifyLearningStateUpdated } from "./learning-events";

type Citation = { rank: number; documentId: string; title: string; excerpt: string; relativeRelevance: number; combinedScore: number; vectorScore: number; lexicalScore: number; authorityBoost?: number; url?: string | null; versionLabel?: string | null; trustLevel?: string };
type Conflict = { title: string; versions: string[]; preferredVersion?: string | null; preferenceReason?: "authority" | "newer_version" | "uncertain" };
type CoachResponse = { error?: string; conversationId?: string; answer?: string; followUp?: string; diagnosis?: string; feedback?: string; nextTask?: string; question?: string; focus?: string; source?: string; issueLabel?: string; teachingMode?: string; delivery?: { mode?: string }; retrieval?: { matches?: Citation[]; conflicts?: Conflict[]; mode?: string } };

function conflictSummary(item: Conflict) {
  const recommendation = item.preferredVersion ? `，建议 ${item.preferredVersion}（${item.preferenceReason === "authority" ? "可信等级更高" : "版本更新"}）` : "，暂时无法可靠判断优先版本";
  return `${item.title}（${item.versions.join(" / ")}）${recommendation}`;
}

export function CoachChat() {
  const [question, setQuestion] = useState(""); const [lastQuestion, setLastQuestion] = useState(""); const [reply, setReply] = useState<CoachResponse>(); const [error, setError] = useState(""); const [citations, setCitations] = useState<Citation[]>([]); const [conflicts, setConflicts] = useState<Conflict[]>([]); const [retrievalMode, setRetrievalMode] = useState(""); const [asking, setAsking] = useState(false); const [rating, setRating] = useState(""); const [ratingError, setRatingError] = useState(""); const [showReasons, setShowReasons] = useState(false);
  async function ask(message = question) { if (!message.trim()) return; setLastQuestion(message); setAsking(true); setReply(undefined); setRating(""); setRatingError(""); setShowReasons(false); setError(""); setCitations([]); setConflicts([]); setRetrievalMode(""); try { const response = await fetch("/api/coach", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message }) }); const body = await response.text(); let data: CoachResponse; try { data = JSON.parse(body) as CoachResponse; } catch { setError(`老师服务返回了异常响应（HTTP ${response.status}）。请稍后重试；如果持续出现，请联系管理员查看 Worker 日志。`); return; } if (!response.ok || data.error) { setError(data.error ?? "老师服务暂时不可用。"); return; } setReply(data); setCitations(data.retrieval?.matches ?? []); setConflicts(data.retrieval?.conflicts ?? []); setRetrievalMode(data.retrieval?.mode ?? ""); setQuestion(""); notifyLearningStateUpdated(); } catch { setError("无法连接老师服务，请检查网络后重试。已有学习记录不会受到影响。"); } finally { setAsking(false); } }
  async function rate(value: "helpful" | "unhelpful", reason?: string) { if (!reply?.conversationId || rating) return; setRatingError(""); try { const response = await fetch("/api/coach/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ conversationId: reply.conversationId, rating: value, reason }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "反馈失败"); setRating(value); setShowReasons(false); } catch (failure) { setRatingError(failure instanceof Error ? failure.message : "反馈失败"); } }
  return <section className="panel side-panel coach-chat"><div className="side-title"><span className="coach-avatar">建</span><div><h2>问老师</h2><p>基于你的学习记录回答</p></div><span className="online-dot" /></div><textarea className="coach-textarea compact-input" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="例如：description 和 schema 的边界是什么？"/><button className="action-button full-button" onClick={() => void ask()} disabled={asking || !question.trim()}>{asking ? "思考中…" : "发送问题"}<span>→</span></button>{error && <p className="answer-box">{error}</p>}{reply && <div className="coach-diagnosis">{reply.delivery?.mode === "fallback" && <p className="coach-fallback">⚠ 当前 AI 渠道不可用，已使用本地课程规则回答。</p>}<section><span>卡点判断 {reply.issueLabel && <b className="coach-issue-label">{reply.issueLabel}</b>}</span><strong>{reply.diagnosis ?? `当前需要巩固 ${reply.focus ?? "相关能力"}`}</strong></section><section><span>老师反馈</span><p>{reply.feedback ?? reply.answer}</p></section><section className="coach-next"><span>下一步</span><strong>{reply.nextTask ?? reply.followUp}</strong><p>验收问题：{reply.question ?? reply.followUp}</p></section><small>依据：{reply.source}</small><div className="coach-rating"><span>{rating === "unhelpful" ? "反馈已记录，可以立即重试" : rating ? "感谢反馈" : showReasons ? "主要问题是？" : "这次回答解决问题了吗？"}</span>{!rating && !showReasons && <div><button onClick={() => void rate("helpful")}>有帮助</button><button onClick={() => setShowReasons(true)}>没解决</button></div>}{showReasons && <div className="coach-rating-reasons"><button onClick={() => void rate("unhelpful", "inaccurate")}>内容不准确</button><button onClick={() => void rate("unhelpful", "misunderstood")}>没理解问题</button><button onClick={() => void rate("unhelpful", "unactionable")}>步骤不可执行</button><button onClick={() => void rate("unhelpful", "irrelevant_source")}>资料不相关</button></div>}{rating === "unhelpful" && <button className="coach-retry" disabled={asking || !lastQuestion} onClick={() => void ask(lastQuestion)}>让老师重新回答</button>}{ratingError && <em>{ratingError}</em>}</div></div>}{conflicts.length > 0 && <p className="retrieval-conflict">⚠ 召回资料存在多个版本：{conflicts.map(conflictSummary).join("；")}</p>}{citations.length > 0 && <details className="coach-citations"><summary>查看 {citations.length} 条召回依据 · {retrievalMode}</summary>{citations.map((citation) => <article key={`${citation.documentId}-${citation.rank}`}><div><b>#{citation.rank} {citation.title}{citation.versionLabel ? `（${citation.versionLabel}）` : ""}</b><span>相对相关性 {citation.relativeRelevance}%</span></div><p>{citation.excerpt}</p><small>综合 {citation.combinedScore} · 向量 {citation.vectorScore} · 关键词 {citation.lexicalScore} · 可信度加权 +{citation.authorityBoost ?? 0} · {citation.trustLevel || "reference"}</small>{citation.url && <a href={citation.url} target="_blank" rel="noreferrer">查看来源 ↗</a>}</article>)}</details>}</section>;
}
