"use client";
import { useState } from "react";
import { notifyLearningStateUpdated } from "./learning-events";

type Citation = { rank: number; documentId: string; title: string; excerpt: string; relativeRelevance: number; combinedScore: number; vectorScore: number; lexicalScore: number; authorityBoost?: number; url?: string | null; versionLabel?: string | null; trustLevel?: string };
type Conflict = { title: string; versions: string[] };

export function CoachChat() {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [citations, setCitations] = useState<Citation[]>([]); const [conflicts, setConflicts] = useState<Conflict[]>([]); const [retrievalMode, setRetrievalMode] = useState(""); const [asking, setAsking] = useState(false);
  async function ask() { setAsking(true); setCitations([]); setConflicts([]); setRetrievalMode(""); try { const response = await fetch("/api/coach", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: question }) }); const data = await response.json(); const notice = data.delivery?.mode === "fallback" ? "⚠ 当前 AI 渠道不可用，已使用本地课程规则回答。你的学习记录没有受到影响。\n\n" : ""; setAnswer(data.error ?? `${notice}${data.answer}\n\n追问：${data.followUp}\n依据：${data.source}`); if (response.ok) { setCitations(data.retrieval?.matches ?? []); setConflicts(data.retrieval?.conflicts ?? []); setRetrievalMode(data.retrieval?.mode ?? ""); setQuestion(""); notifyLearningStateUpdated(); } } catch { setAnswer("老师暂时无法连接，请稍后重试。已有学习记录不会受到影响。"); } finally { setAsking(false); } }
  return <section className="panel side-panel coach-chat"><div className="side-title"><span className="coach-avatar">建</span><div><h2>问老师</h2><p>基于你的学习记录回答</p></div><span className="online-dot" /></div><textarea className="coach-textarea compact-input" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="例如：description 和 schema 的边界是什么？"/><button className="action-button full-button" onClick={ask} disabled={asking || !question.trim()}>{asking ? "思考中…" : "发送问题"}<span>→</span></button>{answer && <p className="answer-box">{answer}</p>}{conflicts.length > 0 && <p className="retrieval-conflict">⚠ 召回资料存在多个版本：{conflicts.map((item) => `${item.title}（${item.versions.join(" / ")}）`).join("；")}</p>}{citations.length > 0 && <details className="coach-citations"><summary>查看 {citations.length} 条召回依据 · {retrievalMode}</summary>{citations.map((citation) => <article key={`${citation.documentId}-${citation.rank}`}><div><b>#{citation.rank} {citation.title}{citation.versionLabel ? `（${citation.versionLabel}）` : ""}</b><span>相对相关性 {citation.relativeRelevance}%</span></div><p>{citation.excerpt}</p><small>综合 {citation.combinedScore} · 向量 {citation.vectorScore} · 关键词 {citation.lexicalScore} · 可信度加权 +{citation.authorityBoost ?? 0} · {citation.trustLevel || "reference"}</small>{citation.url && <a href={citation.url} target="_blank" rel="noreferrer">查看来源 ↗</a>}</article>)}</details>}</section>;
}
