import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) };
export const learnerProfiles = sqliteTable("learner_profiles", { id: text("id").primaryKey(), displayName: text("display_name").notNull(), learningGoal: text("learning_goal").notNull(), weeklyHours: integer("weekly_hours").notNull(), timezone: text("timezone").notNull(), currentProject: text("current_project"), ...timestamps });
export const competencies = sqliteTable("competencies", { id: text("id").primaryKey(), name: text("name").notNull(), description: text("description").notNull(), priority: text("priority").notNull(), prerequisitesJson: text("prerequisites_json").notNull(), ...timestamps });
export const competencyStates = sqliteTable("competency_states", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), mastery: integer("mastery").notNull().default(0), confidence: integer("confidence").notNull().default(0), lastAssessedAt: text("last_assessed_at"), reviewDueAt: text("review_due_at"), rationale: text("rationale").notNull(), ...timestamps }, (t) => [uniqueIndex("uq_state_learner_competency").on(t.learnerId, t.competencyId), index("idx_state_learner_review").on(t.learnerId, t.reviewDueAt)]);
export const learningTasks = sqliteTable("learning_tasks", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), title: text("title").notNull(), instruction: text("instruction").notNull(), expectedOutput: text("expected_output").notNull(), rubricJson: text("rubric_json").notNull(), status: text("status").notNull(), sourceUnitId: text("source_unit_id"), ...timestamps }, (t) => [index("idx_task_learner_status").on(t.learnerId, t.status, t.updatedAt)]);
export const evidence = sqliteTable("evidence", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), taskId: text("task_id").references(() => learningTasks.id), type: text("type").notNull(), content: text("content").notNull(), score: integer("score"), feedback: text("feedback"), ...timestamps }, (t) => [index("idx_evidence_learner_competency").on(t.learnerId, t.competencyId, t.createdAt)]);
export const conversations = sqliteTable("conversations", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), role: text("role").notNull(), content: text("content").notNull(), source: text("source"), metadataJson: text("metadata_json"), ...timestamps }, (t) => [index("idx_conversation_learner_created").on(t.learnerId, t.createdAt)]);
export const assessments = sqliteTable("assessments", { id: text("id").primaryKey(), learnerId: text("learner_id").notNull().references(() => learnerProfiles.id), competencyId: text("competency_id").notNull().references(() => competencies.id), question: text("question").notNull(), rubricJson: text("rubric_json").notNull(), answer: text("answer"), score: integer("score"), feedback: text("feedback"), status: text("status").notNull(), ...timestamps }, (t) => [index("idx_assessment_learner_status").on(t.learnerId, t.status, t.createdAt)]);
export const knowledgeSubmissions = sqliteTable("knowledge_submissions", { id: text("id").primaryKey(), submittedBy: text("submitted_by").notNull(), submitterName: text("submitter_name"), fileName: text("file_name").notNull(), mimeType: text("mime_type").notNull(), fileSize: integer("file_size").notNull(), objectKey: text("object_key"), status: text("status").notNull().default("queued"), attempt: integer("attempt").notNull().default(0), conversion: text("conversion"), characterCount: integer("character_count").notNull().default(0), partCount: integer("part_count").notNull().default(0), duplicateCount: integer("duplicate_count").notNull().default(0), error: text("error"), ...timestamps }, (t) => [index("idx_submission_user_created").on(t.submittedBy, t.createdAt), index("idx_submission_status_created").on(t.status, t.createdAt)]);
export const sourceDocuments = sqliteTable("source_documents", { id: text("id").primaryKey(), title: text("title").notNull(), url: text("url").notNull(), sourceType: text("source_type").notNull(), sourceFileName: text("source_file_name"), sourceMimeType: text("source_mime_type"), submittedBy: text("submitted_by"), submissionId: text("submission_id").references(() => knowledgeSubmissions.id, { onDelete: "set null" }), versionLabel: text("version_label"), reviewedAt: text("reviewed_at"), archivedAt: text("archived_at"), trustLevel: text("trust_level").notNull(), status: text("status").notNull(), topicIdsJson: text("topic_ids_json").notNull(), summary: text("summary"), content: text("content"), contentHash: text("content_hash"), ingestionStatus: text("ingestion_status").notNull().default("pending"), chunkCount: integer("chunk_count").notNull().default(0), lastIndexedAt: text("last_indexed_at"), ingestionError: text("ingestion_error"), ...timestamps }, (t) => [uniqueIndex("uq_source_url_version").on(t.url, t.versionLabel), index("idx_source_status_ingestion").on(t.status, t.ingestionStatus), index("idx_source_submitted_by").on(t.submittedBy, t.createdAt), index("idx_source_submission").on(t.submissionId)]);
export const knowledgeChunks = sqliteTable("knowledge_chunks", { id: text("id").primaryKey(), sourceDocumentId: text("source_document_id").notNull().references(() => sourceDocuments.id, { onDelete: "cascade" }), ordinal: integer("ordinal").notNull(), content: text("content").notNull(), contentHash: text("content_hash").notNull(), tokenEstimate: integer("token_estimate").notNull(), vectorId: text("vector_id").notNull(), status: text("status").notNull().default("pending"), indexedAt: text("indexed_at"), ...timestamps }, (t) => [uniqueIndex("uq_chunk_source_ordinal").on(t.sourceDocumentId, t.ordinal), uniqueIndex("uq_chunk_vector_id").on(t.vectorId), index("idx_chunk_source_status").on(t.sourceDocumentId, t.status)]);
export const knowledgeJobs = sqliteTable("knowledge_jobs", { id: text("id").primaryKey(), sourceDocumentId: text("source_document_id").notNull().references(() => sourceDocuments.id, { onDelete: "cascade" }), type: text("type").notNull(), status: text("status").notNull().default("queued"), attempt: integer("attempt").notNull().default(0), requestedBy: text("requested_by"), startedAt: text("started_at"), finishedAt: text("finished_at"), error: text("error"), ...timestamps }, (t) => [index("idx_knowledge_job_status_created").on(t.status, t.createdAt), index("idx_knowledge_job_document_created").on(t.sourceDocumentId, t.createdAt)]);
export const knowledgeRetrievalLogs = sqliteTable("knowledge_retrieval_logs", { id: text("id").primaryKey(), learnerId: text("learner_id"), query: text("query").notNull(), retrievalMode: text("retrieval_mode").notNull(), resultCount: integer("result_count").notNull(), matchesJson: text("matches_json").notNull(), durationMs: integer("duration_ms").notNull(), vectorError: text("vector_error"), ...timestamps }, (t) => [index("idx_retrieval_created").on(t.createdAt), index("idx_retrieval_mode_created").on(t.retrievalMode, t.createdAt)]);
export const knowledgeEvalCases = sqliteTable("knowledge_eval_cases", { id: text("id").primaryKey(), question: text("question").notNull(), expectedDocumentId: text("expected_document_id").references(() => sourceDocuments.id, { onDelete: "set null" }), expectedTermsJson: text("expected_terms_json").notNull(), status: text("status").notNull().default("active"), lastRunAt: text("last_run_at"), lastMode: text("last_mode"), lastPassed: integer("last_passed", { mode: "boolean" }), lastMatchesJson: text("last_matches_json"), lastError: text("last_error"), ...timestamps }, (t) => [index("idx_eval_status_updated").on(t.status, t.updatedAt)]);
export const aiChannels = sqliteTable("ai_channels", { id: text("id").primaryKey(), slug: text("slug").notNull(), displayName: text("display_name").notNull(), protocol: text("protocol").notNull(), baseUrl: text("base_url").notNull(), model: text("model").notNull(), priority: integer("priority").notNull().default(100), enabled: integer("enabled", { mode: "boolean" }).notNull().default(true), ...timestamps }, (t) => [uniqueIndex("uq_ai_channel_slug").on(t.slug), index("idx_ai_channel_enabled_priority").on(t.enabled, t.priority)]);
export const aiApiKeys = sqliteTable("ai_api_keys", { id: text("id").primaryKey(), channelId: text("channel_id").notNull().references(() => aiChannels.id, { onDelete: "cascade" }), label: text("label").notNull(), encryptedKey: text("encrypted_key").notNull(), keyHint: text("key_hint").notNull(), enabled: integer("enabled", { mode: "boolean" }).notNull().default(true), lastUsedAt: text("last_used_at"), failureCount: integer("failure_count").notNull().default(0), lastError: text("last_error"), ...timestamps }, (t) => [index("idx_ai_key_channel_enabled").on(t.channelId, t.enabled)]);
