"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type UploadResult = { filename: string; ok: boolean; queued?: boolean; error?: string };
type Submission = { id: string; fileName: string; fileSize: number; overallStage: string; characterCount: number; partCount: number; duplicateCount: number; error?: string | null; createdAt: string; stageCounts: Record<string, number>; parts: { id: string; title: string; status: string; ingestionStatus: string }[] };
const accept = ".pdf,.jpg,.jpeg,.png,.webp,.svg,.gif,.bmp,.html,.htm,.xml,.xlsx,.xlsm,.xlsb,.xls,.et,.docx,.ods,.odt,.csv,.numbers,.txt,.md,.markdown";
const stageLabels: Record<string, { label: string; detail: string }> = {
  queued: { label: "排队中", detail: "文件已安全保存，等待后台转换" }, processing: { label: "转换中", detail: "正在提取和整理文档正文" }, failed: { label: "处理失败", detail: "文件未能转换为知识草稿" }, withdrawn: { label: "已撤回", detail: "原文件和待审批草稿已经删除" }, duplicate: { label: "内容重复", detail: "知识库已有相同正文，没有重复保存" }, pending_review: { label: "待管理员审批", detail: "尚未参与 Coach 召回" }, pending_index: { label: "审批通过，待向量化", detail: "管理员尚未建立召回索引" }, index_failed: { label: "向量化失败", detail: "管理员可以查看错误并重试" }, live: { label: "已进入知识库", detail: "Coach 可以召回这份资料" }, archived: { label: "已归档", detail: "已经退出 Coach 召回" },
};
function formatBytes(value: number) { if (!value) return "历史记录"; return value < 1024 * 1024 ? `${Math.max(1, Math.round(value / 1024))} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }

export function KnowledgeUploader() {
  const [files, setFiles] = useState<File[]>([]); const [results, setResults] = useState<UploadResult[]>([]); const [submissions, setSubmissions] = useState<Submission[]>([]); const [uploading, setUploading] = useState(false); const [historyError, setHistoryError] = useState("");
  const loadSubmissions = useCallback(async () => { const response = await fetch("/api/knowledge/mine"); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "上传记录加载失败"); setSubmissions(data.submissions ?? []); }, []);
  useEffect(() => { const timer = setTimeout(() => void loadSubmissions().catch((error) => setHistoryError(error.message)), 0); return () => clearTimeout(timer); }, [loadSubmissions]);
  useEffect(() => { if (!submissions.some((item) => item.overallStage === "queued" || item.overallStage === "processing")) return; const timer = setInterval(() => void loadSubmissions().catch(() => {}), 2500); return () => clearInterval(timer); }, [loadSubmissions, submissions]);
  async function upload() {
    setUploading(true); setResults([]); const next: UploadResult[] = [];
    for (const file of files) {
      try { const form = new FormData(); form.set("file", file); const response = await fetch("/api/knowledge/upload", { method: "POST", body: form }); const data = await response.json(); next.push(response.ok ? { filename: file.name, ok: true, queued: true } : { filename: file.name, ok: false, error: data.error ?? "上传失败" }); }
      catch { next.push({ filename: file.name, ok: false, error: "网络或转换服务暂不可用" }); }
      setResults([...next]); await loadSubmissions().catch(() => {});
    }
    setUploading(false); setFiles([]);
  }
  async function retry(submission: Submission) { const response = await fetch("/api/knowledge/mine", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ submissionId: submission.id }) }); const data = await response.json(); if (!response.ok) return setHistoryError(data.error ?? "重试失败"); setHistoryError(""); await loadSubmissions(); }
  async function withdraw(submission: Submission) { if (!confirm(`撤回“${submission.fileName}”？原文件和待审批草稿会被删除。`)) return; const response = await fetch(`/api/knowledge/mine?submissionId=${encodeURIComponent(submission.id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) return setHistoryError(data.error ?? "撤回失败"); setHistoryError(""); await loadSubmissions(); }
  return <main className="admin-shell upload-shell"><header className="admin-header"><div><Link href="/" className="back-link">← 返回学习页</Link><h1>我的知识资料</h1><p>上传资料并跟踪转换、审批、向量化和归档状态。</p></div><Link href="/admin/knowledge" className="secondary-button">管理员知识库</Link></header>
    <section className="channel-card upload-card"><h2>提交新资料</h2><p>支持 PDF、图片、Word、Excel、HTML/XML、CSV、OpenDocument、Numbers、Markdown 和 TXT。</p><label className="upload-drop"><input key={files.length ? "selected" : "empty"} type="file" accept={accept} multiple disabled={uploading} onChange={(event) => setFiles(Array.from(event.target.files ?? []).slice(0, 10))} /><strong>{files.length ? `已选择 ${files.length} 个文件` : "选择文件或拖入此区域"}</strong><span>单文件最大 20 MB，每次最多 10 个；上传后由后台转换，可以离开页面。</span></label><button className="primary-button" disabled={uploading || !files.length} onClick={upload}>{uploading ? "正在安全上传…" : "上传并排队"}</button>{results.length > 0 && <div className="upload-results">{results.map((result) => <article key={result.filename} className={result.ok ? "success" : "failed"}><strong>{result.filename}</strong><span>{result.ok ? "文件已保存并进入后台转换队列" : result.error}</span></article>)}</div>}</section>
    <section className="submission-history"><div className="knowledge-list-heading"><div><h2>上传记录</h2><p>这里只显示你本人提交的资料。</p></div><button className="secondary-button" onClick={() => void loadSubmissions().catch((error) => setHistoryError(error.message))}>刷新状态</button></div>{historyError && <p className="result-message">{historyError}</p>}{submissions.length === 0 ? <p className="empty-copy">还没有上传记录。</p> : submissions.map((submission) => { const stage = stageLabels[submission.overallStage] ?? stageLabels.processing; const canWithdraw = !submission.id.startsWith("legacy-") && ["failed", "duplicate", "pending_review"].includes(submission.overallStage); return <article key={submission.id}><div className="submission-head"><div><strong>{submission.fileName}</strong><small>{formatBytes(submission.fileSize)} · {new Date(submission.createdAt).toLocaleString("zh-CN")}</small></div><span className={`submission-stage stage-${submission.overallStage}`}>{stage.label}</span></div><p>{stage.detail}</p><div className="submission-meta"><span>{submission.characterCount.toLocaleString()} 字符</span><span>{submission.partCount} 个分片</span>{submission.duplicateCount > 0 && <span>{submission.duplicateCount} 个重复</span>}{Object.entries(submission.stageCounts).map(([key, count]) => <span key={key}>{stageLabels[key]?.label ?? key} {count}</span>)}</div>{submission.error && <em>{submission.error}</em>}<div className="submission-actions">{submission.overallStage === "failed" && !submission.id.startsWith("legacy-") && <button className="secondary-button" onClick={() => void retry(submission)}>重新排队</button>}{canWithdraw && <button className="danger-button" onClick={() => void withdraw(submission)}>撤回资料</button>}</div>{submission.parts.length > 1 && <details><summary>查看 {submission.parts.length} 个资料分片</summary><ul>{submission.parts.map((part) => { const partStage = part.status === "archived" ? "archived" : part.status === "draft" ? "pending_review" : part.ingestionStatus === "indexed" || part.ingestionStatus === "lexical" ? "live" : part.ingestionStatus === "failed" ? "index_failed" : "pending_index"; return <li key={part.id}>{part.title} · {stageLabels[partStage]?.label}</li>; })}</ul></details>}</article>; })}</section>
    <aside className="security-note"><strong>内容安全</strong><span>上传资料只作为草稿保存。管理员必须检查来源、版权、敏感信息和正文质量，再批准向量化。</span></aside>
  </main>;
}
